### ISSUE TITLE
Fix `on_idle` hook to process deposits in thea pallet

### ISSUE THREAD

**Issue by 35359595** [Polkadex-Substrate/Polkadex#677] opened 2023-03-27 09:44 UTC
Fix commented implementation to process approved deposits while there's still time between block productions.

**Comment by pavankanteti** [comment] 2023-06-22 08:35
Duplicate of https://github.com/Polkadex-Substrate/issue-tracker/issues/214

**Closed as completed by pavankanteti** 2023-06-22 08:35 UTC
Labels: enhancement, feature
